-- Backfill every unique product represented by the Website SEO workbook sheet.
-- Where multiple historical URLs resolve to one product, this field keeps the
-- product's canonical old-site URL and ih_redirects retains the extra aliases.
WITH legacy_urls(product_slug, legacy_url) AS (
  VALUES
    ('abundant-tetraploid', 'https://irwinhunter.com.au/product/abundant-tetraploid/'),
    ('achieve-diploid-italian-ryegrass', 'https://irwinhunter.com.au/product/achieve-diploid-italian-ryegrass/'),
    ('alpha-1', 'https://irwinhunter.com.au/product/alpha-1/'),
    ('amass-tetraploid-italian-ryegrass', 'https://irwinhunter.com.au/product/amass-tetraploid-italian-ryegrass/'),
    ('amazon-t', 'https://irwinhunter.com.au/product/amazon-t/'),
    ('amplify-phalaris', 'https://irwinhunter.com.au/product/amplify-phalaris/'),
    ('anywhere-tall-fescue', 'https://irwinhunter.com.au/product/anywhere-tall-fescue/'),
    ('arrowleaf-clover', 'https://irwinhunter.com.au/product/arrowleaf-clover/'),
    ('ausvic', 'https://irwinhunter.com.au/product/ausvic/'),
    ('avalon-persistent-perennial-ryegrass', 'https://irwinhunter.com.au/product/avalon-persistent-perennial-ryegrass/'),
    ('bartolo-bladder-clover', 'https://irwinhunter.com.au/product/bartolo-bladder-clover/'),
    ('bermuda-couch-speedie-coated', 'https://irwinhunter.com.au/product/bermuda-couch-speedie-coated/'),
    ('bio-npk-powder-s', 'https://irwinhunter.com.au/product/bio-npk-powder-s/'),
    ('bounty-forage-sorghum', 'https://irwinhunter.com.au/product/bounty-forage-sorghum/'),
    ('buster-tillage-radish', 'https://irwinhunter.com.au/product/buster-tillage-radish/'),
    ('cadiz-french-serradella', 'https://irwinhunter.com.au/product/cadiz-french-serradella/'),
    ('callide-rhodes-grass', 'https://irwinhunter.com.au/product/callide-rhodes-grass/'),
    ('casbah-biserrulu', 'https://irwinhunter.com.au/product/casbah-biserrulu/'),
    ('cereal-rye', 'https://irwinhunter.com.au/product/cereal-rye/'),
    ('common-vetch', 'https://irwinhunter.com.au/product/common-vetch/'),
    ('cover-crop-plus-summer-mix', 'https://irwinhunter.com.au/product/cover-crop-plus-summer-mix/'),
    ('cover-crop-plus-winter-mix', 'https://irwinhunter.com.au/product/cover-crop-plus-winter-mix/'),
    ('cowpea-ebony', 'https://irwinhunter.com.au/product/cowpea-ebony/'),
    ('crimson-clover', 'https://irwinhunter.com.au/product/crimson-clover/'),
    ('dalkeith-subterranean-clover', 'https://irwinhunter.com.au/product/dalkeith-subterranean-clover/'),
    ('dargo', 'https://irwinhunter.com.au/product/dargo/'),
    ('eliza-serradella', 'https://irwinhunter.com.au/product/eliza-serradella/'),
    ('equi1st-mix', 'https://irwinhunter.com.au/product/equi1st-mix/'),
    ('finecut-rhodes-grass', 'https://irwinhunter.com.au/product/finecut-rhodes-grass/'),
    ('finefeed-diploid-annual-ryegrass', 'https://irwinhunter.com.au/product/finefeed-diploid-annual-ryegrass/'),
    ('fran2o-serradella', 'https://irwinhunter.com.au/product/fran2o-serradella/'),
    ('gatton-panic', 'https://irwinhunter.com.au/product/gatton-panic/'),
    ('green-manure-mix', 'https://irwinhunter.com.au/product/green-manure-mix/'),
    ('haifa-white-clover', 'https://irwinhunter.com.au/product/haifa-white-clover/'),
    ('hard-seeded-persian-clover', 'https://irwinhunter.com.au/product/hard-seeded-persian-clover/'),
    ('hykon-rose-clover', 'https://irwinhunter.com.au/product/hykon-rose-clover/'),
    ('icon-lucerne', 'https://irwinhunter.com.au/product/icon-lucerne/'),
    ('interow-mix', 'https://irwinhunter.com.au/product/interow-mix/'),
    ('irrigation-mix', 'https://irwinhunter.com.au/product/irrigation-mix/'),
    ('katambora-rhodes-grass', 'https://irwinhunter.com.au/product/katambora-rhodes-grass/'),
    ('kyambro-persian-clover', 'https://irwinhunter.com.au/product/kyambro-persian-clover/'),
    ('l97-lucerne', 'https://irwinhunter.com.au/product/l97-lucerne/'),
    ('margurita-french-serradella', 'https://irwinhunter.com.au/product/margurita-french-serradella/'),
    ('matua-prairie-grass', 'https://irwinhunter.com.au/product/matua-prairie-grass/'),
    ('maximix', 'https://irwinhunter.com.au/product/maximix/'),
    ('misson-veldt-grass', 'https://irwinhunter.com.au/product/misson-veldt-grass/'),
    ('nemnuke-biofumigant', 'https://irwinhunter.com.au/product/nemnuke-biofumigant/'),
    ('new-tetila', 'https://irwinhunter.com.au/product/new-tetila/'),
    ('nitro-mix', 'https://irwinhunter.com.au/product/nitro-mix/'),
    ('northern-perennial-pasture-mix', 'https://irwinhunter.com.au/product/northern-perennial-pasture-mix/'),
    ('paradana-balansa-clover', 'https://irwinhunter.com.au/product/paradana-balansa-clover/'),
    ('parafield-peas', 'https://irwinhunter.com.au/product/parafield-peas/'),
    ('prima-gland-clover', 'https://irwinhunter.com.au/product/prima-gland-clover/'),
    ('puccinellia', 'https://irwinhunter.com.au/product/puccinellia/'),
    ('reclaimer-rhodes-grass', 'https://irwinhunter.com.au/product/reclaimer-rhodes-grass/'),
    ('riverina-sub-clover', 'https://irwinhunter.com.au/product/riverina-sub-clover/'),
    ('safeguard-annual-ryegrass', 'https://irwinhunter.com.au/product/safeguard-annual-ryegrass/'),
    ('saia-oats', 'https://irwinhunter.com.au/product/saia-oats/'),
    ('santorini-yellow-serradella', 'https://irwinhunter.com.au/product/santorini-yellow-serradella/'),
    ('sceptre-lucerne', 'https://irwinhunter.com.au/product/sceptre-lucerne/'),
    ('seaton-park', 'https://irwinhunter.com.au/product/seaton-park/'),
    ('self-regeneration-pasture-mix', 'https://irwinhunter.com.au/product/self-regeneration-pasture-mix/'),
    ('shaftal-persian-clover', 'https://irwinhunter.com.au/product/shaftal-persian-clover/'),
    ('shirohie-millet', 'https://irwinhunter.com.au/product/shirohie-millet/'),
    ('silahay-mix', 'https://irwinhunter.com.au/product/silahay-mix/'),
    ('souwest-pasture-mix-2', 'https://irwinhunter.com.au/product/souwest-pasture-mix-2/'),
    ('strawberry-clover', 'https://irwinhunter.com.au/product/strawberry-clover/'),
    ('sunflower-seed', 'https://irwinhunter.com.au/product/sunflower-seed/'),
    ('teff-grass', 'https://irwinhunter.com.au/product/teff-grass/'),
    ('tonic-plantain', 'https://irwinhunter.com.au/product/tonic-plantain/'),
    ('tyrrell-tall-wheat-grass', 'https://irwinhunter.com.au/product/tyrrell-tall-wheat-grass/'),
    ('urana-sub-clover', 'https://irwinhunter.com.au/product/urana-sub-clover/'),
    ('wa-southern-perennial-pasture-mix', 'https://irwinhunter.com.au/product/wa-southern-perennial-pasture-mix/'),
    ('western-annual-ryegrass-mix', 'https://irwinhunter.com.au/product/western-annual-ryegrass-mix/'),
    ('whittet-kikuyu', 'https://irwinhunter.com.au/product/whittet-kikuyu/'),
    ('winfred-forage-brassica', 'https://irwinhunter.com.au/product/winfred-forage-brassica/'),
    ('yarck-cocksfoot', 'https://irwinhunter.com.au/product/yarck-cocksfoot/')
)
UPDATE ih_products AS product
SET website_url_legacy = legacy_urls.legacy_url,
    updated_at = now()
FROM legacy_urls
WHERE product.slug = legacy_urls.product_slug;