import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { createServer } from "node:net";
import { after, before, test } from "node:test";
import { tmpdir } from "node:os";
import { join } from "node:path";

/*
 * This exercises the administrator screen through the same local API process
 * used by the other browser regressions.  The development API bypass is
 * intentional: it is the actor for these requests, while the two persisted
 * administrator rows below are uniquely named fixtures used only for the
 * revocation assertion.  In particular, this test never revokes the
 * development bypass or any pre-existing administrator.
 */

const serverRoot = new URL("..", import.meta.url);
const runId = `browser-admin-${process.pid}-${Date.now()}`;
const chromeBin = process.env.CHROMIUM_BIN ?? "/repl/tools/bin/chromium";
const administratorsPath = "/admin/administrators";
const fixtureAdmins = {
  revoke: {
    clerkUserId: `${runId}-revoke`,
    email: `${runId}-revoke@example.test`,
  },
  retain: {
    clerkUserId: `${runId}-retain`,
    email: `${runId}-retain@example.test`,
  },
};
const pendingEmail = `${runId}-pending@example.test`;

let api;
let chrome;
let cdp;
let baseUrl;
let tempDir;
let requestFailureTriggered = false;
let requestFailureConfig;
let requestFailureListenerInstalled = false;
let interceptionError;
const invitationRequests = [];

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function freePort() {
  const server = createServer();
  await new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address();
  const port = typeof address === "object" && address ? address.port : null;
  await new Promise((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()));
  });
  assert.ok(port, "Expected a free local port");
  return port;
}

async function waitFor(check, label) {
  let lastError;
  for (let attempt = 0; attempt < 150; attempt += 1) {
    try {
      const value = await check();
      if (value) return value;
    } catch (error) {
      lastError = error;
    }
    await delay(100);
  }
  throw new Error(`Timed out waiting for ${label}${lastError ? `: ${lastError.message}` : ""}`);
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sql(query) {
  execFileSync("psql", [
    process.env.DATABASE_URL,
    "-X",
    "-v",
    "ON_ERROR_STOP=1",
    "-c",
    query,
  ], {
    encoding: "utf8",
    stdio: ["ignore", "ignore", "ignore"],
  });
}

function seedFixtureAdmins() {
  const ids = Object.values(fixtureAdmins).map(({ clerkUserId }) => sqlString(clerkUserId)).join(", ");
  sql(`DELETE FROM ih_admin_users WHERE clerk_user_id IN (${ids});
    INSERT INTO ih_admin_users (clerk_user_id, email, role)
    VALUES
      (${sqlString(fixtureAdmins.revoke.clerkUserId)}, ${sqlString(fixtureAdmins.revoke.email)}, 'admin'),
      (${sqlString(fixtureAdmins.retain.clerkUserId)}, ${sqlString(fixtureAdmins.retain.email)}, 'admin');`);
}

function removeOwnedAccessArtifacts() {
  /*
   * Cleanup also covers an interrupted run. Every value matched here is
   * generated by this test's browser-admin namespace; no real administrator
   * uses these structural fixture addresses or ids. Delete audit and
   * revocation history as well as live rows so the screen cannot accumulate
   * stale fixture history between browser runs.
   */
  sql(`DELETE FROM ih_admin_access_audit
    WHERE target_email LIKE 'browser-admin-%-pending@example.test'
       OR target_email LIKE 'browser-admin-%-revoke@example.test'
       OR target_email LIKE 'browser-admin-%-retain@example.test';
    DELETE FROM ih_admin_revocations
    WHERE email LIKE 'browser-admin-%-pending@example.test'
       OR email LIKE 'browser-admin-%-revoke@example.test'
       OR email LIKE 'browser-admin-%-retain@example.test';
    DELETE FROM ih_admin_pending_approvals
    WHERE email LIKE 'browser-admin-%-pending@example.test';
    DELETE FROM ih_admin_users
    WHERE clerk_user_id LIKE 'browser-admin-%-revoke'
       OR clerk_user_id LIKE 'browser-admin-%-retain';`);
}

async function apiResult(method, path, body) {
  const response = await fetch(`${baseUrl}/api${path}`, {
    method,
    headers: body === undefined ? undefined : { "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let data;
  try {
    data = text ? JSON.parse(text) : undefined;
  } catch {
    data = undefined;
  }
  return { response, data };
}

async function apiRequest(method, path, body) {
  const result = await apiResult(method, path, body);
  assert.ok(result.response.ok, `${method} ${path} failed with HTTP ${result.response.status}`);
  return result.data;
}

class Cdp {
  constructor(ws) {
    this.ws = ws;
    this.nextId = 0;
    this.pending = new Map();
    this.listeners = new Map();
    ws.onmessage = ({ data }) => {
      const message = JSON.parse(data);
      if (message.id) {
        const pending = this.pending.get(message.id);
        if (!pending) return;
        this.pending.delete(message.id);
        clearTimeout(pending.timer);
        if (message.error) pending.reject(new Error(message.error.message));
        else pending.resolve(message.result);
        return;
      }
      for (const listener of this.listeners.get(message.method) ?? []) {
        try {
          const result = listener(message.params);
          if (result?.catch) result.catch((error) => { this.listenerError = error; });
        } catch (error) {
          this.listenerError = error;
        }
      }
    };
  }

  call(method, params = {}) {
    const id = ++this.nextId;
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        if (!this.pending.has(id)) return;
        this.pending.delete(id);
        reject(new Error(`CDP ${method} timed out`));
      }, 10000);
      this.pending.set(id, { resolve, reject, timer });
      this.ws.send(JSON.stringify({ id, method, params }));
    });
  }

  on(method, listener) {
    const listeners = this.listeners.get(method) ?? [];
    listeners.push(listener);
    this.listeners.set(method, listeners);
  }

  async evaluate(expression, awaitPromise = false) {
    const result = await this.call("Runtime.evaluate", {
      expression,
      awaitPromise,
      returnByValue: true,
    });
    if (result.exceptionDetails) {
      throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text);
    }
    return result.result.value;
  }
}

function selectorExpression(selector) {
  return JSON.stringify(selector);
}

function regexExpression(regex) {
  return `new RegExp(${JSON.stringify(regex.source)}, ${JSON.stringify(regex.flags)})`;
}

function escapedRegex(text) {
  return new RegExp(String(text).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
}

async function waitForSelector(selector) {
  await waitFor(
    () => cdp.evaluate(`Boolean(document.querySelector(${selectorExpression(selector)}))`),
    selector,
  );
}

async function waitForVisibleText(regex, label = regex.toString()) {
  return waitFor(
    () => cdp.evaluate(`(() => {
      const pattern = ${regexExpression(regex)};
      return Array.from(document.querySelectorAll("body *")).some((element) => {
        if (!element.offsetParent && element.getClientRects().length === 0) return false;
        return pattern.test(element.textContent?.replace(/\\s+/g, " ").trim() || "");
      });
    })()`),
    label,
  );
}

async function waitForVisibleAlert(regex, label = `alert ${regex}`) {
  await waitFor(
    () => cdp.evaluate(`(() => {
      const pattern = ${regexExpression(regex)};
      return Array.from(document.querySelectorAll('[role="alert"]')).some((element) =>
        (element.offsetParent || element.getClientRects().length)
          && pattern.test(element.textContent?.replace(/\\s+/g, " ").trim() || "")
      );
    })()`),
    label,
  );
}

async function clickButtonMatching(regex, label = regex.toString(), scopeSelector = null) {
  const scope = scopeSelector
    ? `document.querySelector(${selectorExpression(scopeSelector)})`
    : "document";
  await waitFor(
    () => cdp.evaluate(`(() => {
      const root = ${scope};
      if (!root) return false;
      const pattern = ${regexExpression(regex)};
      return Array.from(root.querySelectorAll("button")).some((button) =>
        (button.offsetParent || button.getClientRects().length)
          && pattern.test(button.textContent?.replace(/\\s+/g, " ").trim() || "")
          && !button.disabled
      );
    })()`),
    `button ${label}`,
  );
  await cdp.evaluate(`(() => {
    const root = ${scope};
    const pattern = ${regexExpression(regex)};
    const button = Array.from(root.querySelectorAll("button")).find((candidate) =>
      (candidate.offsetParent || candidate.getClientRects().length)
        && pattern.test(candidate.textContent?.replace(/\\s+/g, " ").trim() || "")
        && !candidate.disabled
    );
    button?.click();
    return Boolean(button);
  })()`);
}

async function waitForDialog() {
  await waitFor(
    () => cdp.evaluate(`Array.from(document.querySelectorAll('[role="dialog"], .admin-dialog, .admin-confirm-dialog'))
      .some((dialog) => dialog.offsetParent || dialog.getClientRects().length)`),
    "administrator confirmation dialog",
  );
}

async function confirmAction(kind) {
  await waitForDialog();
  const buttonPattern = kind === "cancel" ? /^Cancel approval$/i : /^Revoke access$/i;
  // These are the explicit destructive labels rendered by ConfirmDialog.
  // Selecting the dialog first avoids accidentally clicking the row action
  // again when the same label is present behind the modal.
  await clickButtonMatching(buttonPattern, `confirm ${kind}`, '[role="dialog"]');
}

async function setViewport(width, height = 900) {
  await cdp.call("Emulation.setDeviceMetricsOverride", {
    width,
    height,
    deviceScaleFactor: 1,
    mobile: width < 800,
  });
}

async function navigate(path) {
  await cdp.call("Page.navigate", { url: `${baseUrl}${path}` });
  await waitFor(
    () => cdp.evaluate('document.readyState === "complete" || document.readyState === "interactive"'),
    `navigation to ${path}`,
  );
}

async function reload() {
  await cdp.call("Page.reload", { ignoreCache: true });
  await waitFor(
    () => cdp.evaluate('document.readyState === "complete" || document.readyState === "interactive"'),
    "page reload",
  );
}

async function setApprovalEmail(email) {
  const encodedEmail = JSON.stringify(email);
  await waitFor(
    () => cdp.evaluate(`Array.from(document.querySelectorAll("input:not([type=hidden])")).some((input) => {
      const metadata = [input.type, input.name, input.id, input.placeholder, input.getAttribute("aria-label")]
        .filter(Boolean).join(" ");
      return input.type === "email" || /email|administrator|approval/i.test(metadata);
    })`),
    "administrator approval email input",
  );
  await cdp.evaluate(`(() => {
    const input = Array.from(document.querySelectorAll("input:not([type=hidden])")).find((candidate) => {
      const metadata = [candidate.type, candidate.name, candidate.id, candidate.placeholder, candidate.getAttribute("aria-label")]
        .filter(Boolean).join(" ");
      return candidate.type === "email" || /email|administrator|approval/i.test(metadata);
    });
    if (!input) return false;
    const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set;
    setter.call(input, ${encodedEmail});
    input.dispatchEvent(new Event("input", { bubbles: true }));
    input.dispatchEvent(new Event("change", { bubbles: true }));
    return true;
  })()`);
}

async function clickApprovalSubmit() {
  await clickButtonMatching(/approve(?:\s+(?:access|administrator|email|request))?/i, "approve administrator");
}

async function clickActionForEmail(email, actionRegex, label) {
  const encodedEmail = JSON.stringify(email);
  await waitFor(
    () => cdp.evaluate(`(() => {
      const email = ${encodedEmail};
      const pattern = ${regexExpression(actionRegex)};
      return Array.from(document.querySelectorAll("button")).some((button) => {
        if (!(button.offsetParent || button.getClientRects().length) || button.disabled
          || !pattern.test(button.textContent?.replace(/\\s+/g, " ").trim() || "")) return false;
        const tableRow = button.closest("tr");
        if (tableRow) return tableRow.textContent?.includes(email);
        let parent = button;
        for (let depth = 0; parent && depth < 8; depth += 1, parent = parent.parentElement) {
          if (parent.textContent?.includes(email) && (parent.textContent?.length ?? Infinity) < 600) return true;
        }
        return false;
      });
    })()`),
    `${label} for ${email}`,
  );
  await cdp.evaluate(`(() => {
    const email = ${encodedEmail};
    const pattern = ${regexExpression(actionRegex)};
    const button = Array.from(document.querySelectorAll("button")).find((candidate) => {
      if (!(candidate.offsetParent || candidate.getClientRects().length) || candidate.disabled
        || !pattern.test(candidate.textContent?.replace(/\\s+/g, " ").trim() || "")) return false;
      const tableRow = candidate.closest("tr");
      if (tableRow) return tableRow.textContent?.includes(email);
      let parent = candidate;
      for (let depth = 0; parent && depth < 8; depth += 1, parent = parent.parentElement) {
        if (parent.textContent?.includes(email) && (parent.textContent?.length ?? Infinity) < 600) return true;
      }
      return false;
    });
    button?.click();
    return Boolean(button);
  })()`);
}

async function waitForNoActionForEmail(email, actionRegex, label) {
  const encodedEmail = JSON.stringify(email);
  await waitFor(
    () => cdp.evaluate(`(() => {
      const email = ${encodedEmail};
      const pattern = ${regexExpression(actionRegex)};
      return !Array.from(document.querySelectorAll("button")).some((button) => {
        if (!(button.offsetParent || button.getClientRects().length)
          || !pattern.test(button.textContent?.replace(/\\s+/g, " ").trim() || "")) return false;
        const tableRow = button.closest("tr");
        if (tableRow) return tableRow.textContent?.includes(email);
        let parent = button;
        for (let depth = 0; parent && depth < 8; depth += 1, parent = parent.parentElement) {
          if (parent.textContent?.includes(email) && (parent.textContent?.length ?? Infinity) < 600) return true;
        }
        return false;
      });
    })()`),
    label,
  );
}

async function assertNoHorizontalOverflow(label) {
  await waitFor(
    () => cdp.evaluate("document.documentElement.scrollWidth <= window.innerWidth + 1 && document.body.scrollWidth <= window.innerWidth + 1"),
    label,
  );
}

function records(data, names) {
  if (Array.isArray(data)) return data;
  for (const name of names) {
    if (Array.isArray(data?.[name])) return data[name];
  }
  return [];
}

function recordEmail(record) {
  return String(record?.email ?? record?.targetEmail ?? record?.address ?? "");
}

async function administratorList() {
  return apiRequest("GET", administratorsPath);
}

async function assertAdministratorList({ activeEmails = [], pendingEmails = [] } = {}) {
  const data = await administratorList();
  const active = records(data, ["active", "activeAdministrators", "administrators"]);
  const pending = records(data, ["pending", "pendingApprovals", "pendingEmails", "approvals"]);
  for (const email of activeEmails) {
    assert.ok(active.some((record) => recordEmail(record).toLowerCase() === email.toLowerCase()), `Active administrator ${email} should be listed`);
  }
  for (const email of pendingEmails) {
    assert.ok(pending.some((record) => recordEmail(record).toLowerCase() === email.toLowerCase()), `Pending approval ${email} should be listed`);
  }
  return { data, active, pending };
}

async function installRequestFailure({ method, urlPart, bodyPattern, message }) {
  requestFailureTriggered = false;
  interceptionError = undefined;
  requestFailureConfig = {
    method,
    urlPart,
    bodyPattern,
    message,
  };
  await cdp.call("Fetch.enable", {
    patterns: [{ urlPattern: "*api/admin/administrators/*", requestStage: "Request" }],
  });
  if (requestFailureListenerInstalled) return;
  requestFailureListenerInstalled = true;
  cdp.on("Fetch.requestPaused", async (event) => {
    try {
      const config = requestFailureConfig;
      const postData = event.request.postData ?? "";
      const shouldFail = config
        && event.request.method === config.method
        && event.request.url.includes(config.urlPart)
        && config.bodyPattern.test(postData);
      if (shouldFail && !requestFailureTriggered) {
        requestFailureTriggered = true;
        const body = Buffer.from(JSON.stringify({ error: config.message })).toString("base64");
        await cdp.call("Fetch.fulfillRequest", {
          requestId: event.requestId,
          responseCode: 503,
          responseHeaders: [{ name: "Content-Type", value: "application/json" }],
          body,
        });
        return;
      }
      await cdp.call("Fetch.continueRequest", { requestId: event.requestId });
    } catch (error) {
      interceptionError = error;
    }
  });
}

async function disableRequestFailure() {
  try {
    await cdp.call("Fetch.disable");
  } catch {
    // Navigation can close Fetch before teardown reaches this helper.
  }
  assert.equal(interceptionError, undefined, "Browser request interception should not fail");
  requestFailureConfig = undefined;
}

before(async () => {
  assert.ok(process.env.DATABASE_URL, "DATABASE_URL is required");
  removeOwnedAccessArtifacts();
  seedFixtureAdmins();
  tempDir = mkdtempSync(join(tmpdir(), "ih-admin-browser-"));

  const apiPort = await freePort();
  baseUrl = `http://127.0.0.1:${apiPort}`;
  api = spawn(process.execPath, ["--enable-source-maps", "./dist/index.mjs"], {
    cwd: new URL(serverRoot).pathname,
    env: {
      ...process.env,
      NODE_ENV: "development",
      PORT: String(apiPort),
    },
    stdio: ["ignore", "ignore", "ignore"],
  });
  await waitFor(async () => (await fetch(`${baseUrl}/api/healthz`)).ok, "isolated API server");

  const chromePort = await freePort();
  chrome = spawn(chromeBin, [
    "--headless=new",
    "--no-sandbox",
    "--disable-gpu",
    `--remote-debugging-port=${chromePort}`,
    `--user-data-dir=${join(tempDir, "chrome")}`,
    "about:blank",
  ], { stdio: "ignore" });
  const target = await waitFor(async () => {
    const response = await fetch(`http://127.0.0.1:${chromePort}/json/list`);
    const pages = await response.json();
    return pages.find((page) => page.type === "page");
  }, "Chromium CDP target");
  const ws = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => {
    ws.onopen = resolve;
    ws.onerror = reject;
  });
  cdp = new Cdp(ws);
  cdp.on("Network.requestWillBeSent", (event) => {
    if (/invitation|invite/i.test(event.request.url)) {
      invitationRequests.push({ method: event.request.method, url: event.request.url });
    }
  });
  await cdp.call("Page.enable");
  await cdp.call("Network.enable");
});

after(async () => {
  cdp?.ws.close();
  chrome?.kill("SIGTERM");
  api?.kill("SIGTERM");
  if (tempDir) rmSync(tempDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
  if (process.env.DATABASE_URL) {
    try {
      removeOwnedAccessArtifacts();
    } catch {
      // Preserve the browser assertion if teardown is interrupted.
    }
  }
});

test("Administrators manages isolated approvals and fixture access on desktop and mobile", async () => {
  await setViewport(1280, 900);
  await navigate(administratorsPath);
  await waitForVisibleText(/^Administrators$/i, "Administrators page");
  await waitForVisibleText(/Active administrators/i, "active administrator list");
  await waitForVisibleText(new RegExp(fixtureAdmins.revoke.email), "isolated revocation fixture");
  await waitForVisibleText(new RegExp(fixtureAdmins.retain.email), "isolated retained fixture");
  await assertAdministratorList({
    activeEmails: [fixtureAdmins.revoke.email, fixtureAdmins.retain.email],
  });

  /*
   * Fail one real approval request at the browser boundary.  This verifies
   * that the form reports a recoverable API error rather than silently
   * claiming that access was granted.
   */
  await installRequestFailure({
    method: "POST",
    urlPart: "/approvals",
    bodyPattern: /"email"\s*:/i,
    message: "Unable to save administrator access. Please try again.",
  });
  await setApprovalEmail(pendingEmail);
  await clickApprovalSubmit();
  await waitFor(() => requestFailureTriggered, "intercepted approval request");
  await waitForVisibleText(/unable to save|could not|try again|failed/i, "approval error message");
  await disableRequestFailure();
  assert.equal(requestFailureTriggered, true);
  assert.equal((await assertAdministratorList()).pending.some((record) => recordEmail(record).toLowerCase() === pendingEmail.toLowerCase()), false);

  /*
   * Approval is a server-side pending email only.  The browser must not
   * request an invitation from Clerk or another email provider.
   */
  await setApprovalEmail(pendingEmail);
  await clickApprovalSubmit();
  await waitForVisibleText(new RegExp(pendingEmail), "new pending approval");
  await waitForVisibleText(/does not create.*(?:Clerk )?account|does not send an invitation|creates no (?:Clerk )?account|sends no email|no invitation/i, "no invitation guidance");
  await waitFor(() => cdp.evaluate(`document.body.textContent?.includes(${JSON.stringify(pendingEmail)})`), "pending email rendered");
  assert.equal(invitationRequests.length, 0, "Approving access must not request an invitation message");
  await assertAdministratorList({ pendingEmails: [pendingEmail] });

  // A reload must retain the pending approval from the real API.
  await reload();
  await waitForVisibleText(/^Administrators$/i, "Administrators page after reload");
  await waitForVisibleText(new RegExp(pendingEmail), "pending approval after reload");
  await assertAdministratorList({ pendingEmails: [pendingEmail] });

  /*
   * Use the narrow layout for the destructive pending action.  The
   * confirmation is deliberately asserted before it is accepted.
   */
  await setViewport(390, 844);
  await reload();
  await waitForVisibleText(/^Administrators$/i, "mobile Administrators page");
  await waitForVisibleText(new RegExp(pendingEmail), "mobile pending approval");
  await assertNoHorizontalOverflow("Administrators has no mobile horizontal overflow");
  await clickActionForEmail(pendingEmail, /cancel\s+(?:approval|request)/i, "cancel pending approval");
  await waitForDialog();
  await waitForVisibleText(/cancel.*(?:approval|pending)|keep.*approval/i, "cancel approval confirmation");
  await installRequestFailure({
    method: "DELETE",
    urlPart: "/approvals",
    bodyPattern: new RegExp(pendingEmail.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")),
    message: "Unable to cancel this approval. Please try again.",
  });
  await confirmAction("cancel");
  await waitFor(() => requestFailureTriggered, "intercepted cancellation request");
  await waitForVisibleAlert(/unable to cancel|failed to cancel|try again/i, "cancel approval error message");
  await disableRequestFailure();
  assert.equal(requestFailureTriggered, true);
  await assertAdministratorList({ pendingEmails: [pendingEmail] });

  // The failed confirmation closes without losing the pending row; retry the
  // same real API action after the one-shot interception is removed.
  await clickActionForEmail(pendingEmail, /cancel\s+(?:approval|request)/i, "retry cancel pending approval");
  await waitForDialog();
  await confirmAction("cancel");
  await waitFor(async () => {
    const list = await assertAdministratorList();
    return list.pending.some((record) => recordEmail(record).toLowerCase() === pendingEmail.toLowerCase()) ? false : true;
  }, "pending approval cancellation");
  // Invalidate/refetch is asynchronous in the UI; reload once the API has
  // confirmed the cancellation so this assertion remains about durable state.
  await reload();
  await waitForVisibleText(/^Administrators$/i, "mobile Administrators after cancellation");
  await waitForNoActionForEmail(pendingEmail, /cancel\s+(?:approval|request)/i, "cancelled pending approval");
  await waitForVisibleText(/audit|access history|activity/i, "administrator audit history");
  await waitForVisibleText(new RegExp(pendingEmail), "cancelled approval in audit history");
  await waitForVisibleText(/Cancelled approval/i, "cancelled approval audit action");

  /*
   * Revoke only the fixture row created above.  The development bypass is
   * intentionally not an item selected by this action.
   */
  await setViewport(1280, 900);
  await waitForVisibleText(new RegExp(fixtureAdmins.revoke.email), "desktop revocation fixture");
  await clickActionForEmail(fixtureAdmins.revoke.email, /revoke\s+access/i, "revoke fixture administrator");
  await waitForDialog();
  await waitForVisibleText(/revoke.*(?:access|administrator)|remove.*administrator/i, "revoke confirmation");
  await installRequestFailure({
    method: "DELETE",
    urlPart: "/access",
    bodyPattern: new RegExp(fixtureAdmins.revoke.clerkUserId.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")),
    message: "Unable to revoke access. Please try again.",
  });
  await confirmAction("revoke");
  await waitFor(() => requestFailureTriggered, "intercepted revocation request");
  await waitForVisibleAlert(/unable to revoke|failed to revoke|try again/i, "revoke access error message");
  await disableRequestFailure();
  assert.equal(requestFailureTriggered, true);
  await assertAdministratorList({
    activeEmails: [fixtureAdmins.revoke.email, fixtureAdmins.retain.email],
  });

  // Retry after the one-shot failed request; only this isolated fixture is
  // selected, never the development bypass or a real administrator row.
  await clickActionForEmail(fixtureAdmins.revoke.email, /revoke\s+access/i, "retry revoke fixture administrator");
  await waitForDialog();
  await confirmAction("revoke");
  await waitFor(async () => {
    const list = await assertAdministratorList({ activeEmails: [fixtureAdmins.retain.email] });
    return list.active.some((record) => recordEmail(record).toLowerCase() === fixtureAdmins.revoke.email.toLowerCase()) ? false : true;
  }, "fixture administrator revocation");
  await waitForVisibleText(/audit|access history|activity/i, "audit history after revocation");
  await waitForVisibleText(new RegExp(fixtureAdmins.revoke.email), "revocation in audit history");
  await waitForVisibleText(/Revoked access/i, "revocation audit action");
  await assertNoHorizontalOverflow("desktop Administrators has no horizontal overflow");
});